---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: runners-metrics-exporter
  name: runners-metrics-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app: runners-metrics-exporter
  type: ClusterIP
